
version: 2

models:
    - name: Top5Runs
      description: "Get last 5 runs"
      columns:
          - name: RunId
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: Top50RunDetails
      description: "Get Last 50 run Details"
      columns:
          - name: PipelineRunId
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
